# Generated by Django 3.1.4 on 2021-01-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210104_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='listing_images'),
        ),
    ]
