# Generated by Django 3.1.4 on 2021-01-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210104_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
