# Generated by Django 3.1.4 on 2021-01-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_listing_listing_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_final_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
