# Generated by Django 3.1.4 on 2021-01-04 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210104_0247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='listing_owener',
            new_name='listing_owner',
        ),
    ]
