# Generated by Django 3.1.5 on 2021-01-05 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20210104_0420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='listing_final_price',
            new_name='final_price',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='listing_open',
            new_name='open_at',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='listing_owner',
            new_name='owner',
        ),
    ]
