# Generated by Django 3.1.5 on 2021-01-08 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20210105_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='final_price',
        ),
    ]
