# Generated by Django 3.1.5 on 2021-01-10 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20210109_2345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
